### PR TITLE
Write the project documentation #9

### PR DESCRIPTION
**Pull request by ioan-h**
This is the first draft of the README file containing all the possible information at this stage of the project.

I believe installation instructions are stable enough and don't require for us to wait until we have the finer details which will be hidden behind the install & build procedures.

### CODE REVIEW

**Comment by ioan-h** [comment]
I would also like to get this changes up into the master branch (PR from feature branch to master) since it's documentation which is displayed on the home page of the project. (You may self approve that change when this PR gets approved)

**Comment by kawazoe** [comment]
The name of the package should match the name of the repository. The current config files uses "angular2-semantic-cy" and not "angular-semantic". The instructions should reflect that.

**Comment by ioan-h** [comment]
Will update config instead.

**Comment by ioan-h** [comment]
Config has been updated to match "angular2-semantic"

**Comment by kawazoe** [comment]
Also, why is there complex instructions for installation when it's just a matter of running `npm install angular2-semantic` --save?

**Comment by ioan-h** [comment]
Fixed instructions to `npm install angular2-semantic --save` and removed the old ones to avoid any potential confusion.

**Pull request merged**
